export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const CLOSE_REGISTER_ERROR_MODAL = "CLOSE_REGISTER_ERROR_MODAL";



