export const GET_NEW_FEED = "GET_NEW_FEED";
export const GET_NEW_FEED_SUCCESS = "GET_NEW_FEED_SUCCESS";

export const POST_STATUS = "POST_STATUS";
export const POST_STATUS_SUCCESS = "POST_STATUS_SUCCESS";

export const GET_NEW_FEED_ERROR = "GET_NEW_FEED_ERROR";
export const CLOSE_GET_NEW_FEED_ERROR_MODAL = "CLOSE_GET_NEW_FEED_ERROR_MODAL";

export const OPEN_MODAL_DELETE = "OPEN_MODAL_DELETE";
export const CLOSE_MODAL_DELETE = "CLOSE_MODAL_DELETE";

export const ARGEE_DELETE = "ARGEE_DELETE";
export const ARGEE_DELETE_SUCCESS = "ARGEE_DELETE_SUCCESS";




