export const ACCEPT_RESET_PASSWORD ="ACCEPT_RESET_PASSWORD";
export const ACCEPT_RESET_PASSWORD_SUCCESS ="ACCEPT_RESET_PASSWORD_SUCCESS"


export const AC_RESET_PASSWORD_ERROR = "AC_RESET_PASSWORD_ERROR";
export const CLOSE_AC_RESET_PASSWORD_ERROR_MODAL = "CLOSE_AC_RESET_PASSWORD_ERROR_MODAL";