export const CHANGE_PASSWORD ="CHANGE_PASSWORD";
export const CHANGE_PASSWORD_SUCCESS ="CHANGE_PASSWORD_SUCCESS"

export const CANCEL_CHANGE_PASSWORD ="CANCEL_CHANGE_PASSWORD"


export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";
export const CLOSE_CHANGE_PASSWORD_ERROR_MODAL = "CLOSE_CHANGE_PASSWORD_ERROR_MODAL";