export const GET_FRIEND_PROFILE = "GET_FRIEND_PROFILE";
export const GET_FRIEND_PROFILE_SUCCESS = "GET_FRIEND_PROFILE_SUCCESS";

export const GET_FRIEND_STATUS = "GET_FRIEND_STATUS";
export const GET_FRIEND_STATUS_SUCCESS = "GET_FRIEND_STATUS_SUCCESS";


export const GET_FRIEND_PROFILE_ERROR = "GET_FRIEND_PROFILE_ERROR";
export const CLOSE_FRIEND_PROFILE_ERROR_MODAL = "CLOSE_FRIEND_PROFILE_ERROR_MODAL";
