export const REQUSET_RESET_PASSWORD ="REQUSET_RESET_PASSWORD";
export const REQUSET_RESET_PASSWORD_SUCCESS ="REQUSET_RESET_PASSWORD_SUCCESS"


export const RE_RESET_PASSWORD_ERROR = "RE_RESET_PASSWORD_ERROR";
export const CLOSE_RE_RESET_PASSWORD_ERROR_MODAL = "CLOSE_RE_RESET_PASSWORD_ERROR_MODAL";