export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";

export const GET_LIST_FRIEND = "GET_LIST_FRIEND";
export const GET_LIST_FRIEND_SUCCESS = "GET_LIST_FRIEND_SUCCESS";

export const GET_STATUS = "GET_STATUS";
export const GET_STATUS_SUCCESS = "GET_STATUS_SUCCESS";

export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";

export const EDIT_PROFILE = "EDIT_PROFILE";
export const EDIT_CANCEL = "EDIT_CANCEL";

export const POST_STATUS_PROFILE = "POST_STATUS_PROFILE";
export const POST_STATUS_PROFILE_SUCCESS = "POST_STATUS_PROFILE_SUCCESS";

export const GET_PROFILE_ERROR = "GET_PROFILE_ERROR";
export const CLOSE_PROFILE_ERROR_MODAL = "CLOSE_PROFILE_ERROR_MODAL";


export const OPEN_MODAL_DELETE_IN_PROFILE = "OPEN_MODAL_DELETE_IN_PROFILE";
export const CLOSE_MODAL_DELETE_IN_PROFILE = "CLOSE_MODAL_DELETE_IN_PROFILE";

export const ARGEE_DELETE_IN_PROFILE = "ARGEE_DELETE_IN_PROFILE";
export const ARGEE_DELETE_IN_PROFILE_SUCCESS = "ARGEE_DELETE_IN_PROFILE_SUCCESS";